--- #YAML:1.0
name: MasonX-Plugin-Compress
version: 0.1
author:
  - David Baird <cpan@riverside-cms.co.uk>
abstract: send compressed output if the client supports it
license: perl
requires:
  Class::Accessor: 0
  Compress::Bzip2: 2
  Compress::Zlib: 0
  HTML::Mason: 1.29
  List::Util: 0
  Test::More: 0
provides:
  MasonX::Plugin::Compress:
    file: lib/MasonX/Plugin/Compress.pm
    version: 0.1
generated_by: Module::Build version 0.2609
